server:
  port: 8080

spring:
  application:
    name: ChatAI
  ai:
    openai:
      base-url: https://api.openai.com
      api-key: sk-proj-oVUsbfNx0XW3g7NL1DA4T3BlbkFJh6WXzK4kR24pHQAgg0YE
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
  datasource:
    driverClassName: org.h2.Driver
          #spring.datasource.url=jdbc:h2:mem:quiz
    username: sa
    password: sa
    #if want  to persist data/save data (not delete after every restart)
    url: jdbc:h2:C:/Users/91757/Desktop/ChatAI/data/bankData
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
